### ISSUE TITLE
returning-a-view-versus-a-copy

### ISSUE THREAD

**Issue by hatemhosny** [sohila846/zika-analysis#3]
I noticed warnings like this:

> C:\Users\E.Mina\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Can you explain that? And how can you solve this?

**Comment by sohila846** [comment]
i fixed that
